### ISSUE TITLE
Build reproducibility on Windows

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j-tools#29]
Jar files generated on Windows do not match those published on Maven Central.

The problem is caused by line endings of resources (in version `0.2.0` just `log4j-changelog.xsd`), which are checked out as CRLF on Windows and LF on UNIX.

**Comment by garydgregory** [comment]
Isn't this usually handled with git config autocrlf?

**Comment by ppkarwasz** [comment]
@garydgregory, locally yes, but the value of `core.autocrlf` is not inherited, when you clone a repository.

I believe that we should add an appropriate `.gitattributes` configuration.
