### ISSUE TITLE
 log4j-changelog is too chatty by default

### ISSUE THREAD

**Issue by garydgregory** [apache/logging-log4j-tools#85]
## Description

Running the plugin with 'mvn clean verify' for Apache Log4j 2.22.0 RC1 is too chatty by default:
```
exported 54 release directories: ..., `C:\tmp\test\src\changelog\2.22.0`
exporting upcoming release directory: `C:\tmp\test\src\changelog\.2.x.x`
```
I don't need to know any of that (IMO of course). That would be best left for debug output.

## Configuration

**Version:**
0.5.0

**Operating system:**
Microsoft Windows [Version 10.0.19045.3570]

**JDK:** 
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment Temurin-11.0.20+8 (build 11.0.20+8)
OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (build 11.0.20+8, mixed mode)

## Logs

```
[INFO] --- log4j-changelog:0.5.0:export (export-changelog) @ log4j-bom ---
[WARNING] The POM for org.apache.logging.log4j:log4j-changelog:jar:0.5.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
exported 54 release directories: ..., `C:\tmp\test\src\changelog\2.22.0`
exporting upcoming release directory: `C:\tmp\test\src\changelog\.2.x.x`
```

## Reproduction

Run `mvn clean verify` on Apache Log4j 2.22.0 RC1.

**Comment by vy** [comment]
Could you elabore it a bit more, please? Consider the following plugin executions:

```
[INFO] --- clean:3.2.0:clean (default-clean) @ log4j-changelog-maven-plugin ---
[INFO] Deleting /home/vy/Projects/log4j-tools/log4j-changelog-maven-plugin/target
[INFO] 
[INFO] --- flatten:1.5.0:clean (clean-flattened-pom) @ log4j-changelog-maven-plugin ---
[INFO] Deleting /home/vy/Projects/log4j-tools/log4j-changelog-maven-plugin/.flattened-pom.xml
[INFO] 
[INFO] --- enforcer:3.3.0:enforce (enforce-upper-bound-deps) @ log4j-changelog-maven-plugin ---
[INFO] Rule 0: org.apache.maven.enforcer.rules.dependency.RequireUpperBoundDeps passed
[INFO] 
[INFO] --- remote-resources:3.1.0:process (process-resource-bundles) @ log4j-changelog-maven-plugin ---
[INFO] Preparing remote bundle org.apache.apache.resources:apache-jar-resource-bundle:1.5
[INFO] Copying 3 resources from 1 bundle.
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ log4j-changelog-maven-plugin ---
[INFO] skip non existing resourceDirectory /home/vy/Projects/log4j-tools/log4j-changelog-maven-plugin/src/main/resources
[INFO] Copying 3 resources from target/maven-shared-archive-resources to target/classes
[INFO] 
[INFO] --- flatten:1.5.0:flatten (flatten-revision) @ log4j-changelog-maven-plugin ---
[INFO] Generating flattened POM of project org.apache.logging.log4j:log4j-changelog-maven-plugin:maven-plugin:0.6.0-SNAPSHOT...
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ log4j-changelog-maven-plugin ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 5 source files with javac [debug release 8] to target/classes
```

All of them display some brief information about what they are doing. Likewise, `log4j-changelog-m-p` states (looking at the log output you shared):

1. It processed 54 release directories and the last one was `C:\tmp\test\src\changelog\2.22.0` – this is good for checking _"Did it really process all my changelog directories?"_
2. It is exporting the upcoming release to `C:\tmp\test\src\changelog\.2.x.x` – this is good for checking _"Are the release notes ready?"_

These convey information that matters, IMO. `flatten-m-p`, `m-compiler-p`, `m-enforcer-p`, `m-clean-p`, etc. all do the same. Do you think these are irrelevant and should be moved to a lower logging level?

**Comment by garydgregory** [comment]
Sigh, I should NOT have to parse pages and pages of Maven output to know if the right thing happened. This is a perfect example of where we are making the situation worse IMO.

What am I supposed to do with:
```
exported 54 release directories: ..., `C:\tmp\test\src\changelog\2.22.0`
exporting upcoming release directory: `C:\tmp\test\src\changelog\.2.x.x`
```

Should I know that the plugin should have processed 55 directories instead of 54? If that's the case, why did the plugin succeed?

**Comment by vy** [comment]
I am not strongly opinionated. I am just telling that we are doing what everybody else is doing. If you think every Maven plugin should have no output by default... Okay. Please submit a PR.

**Comment by ppkarwasz** [comment]
This is the classic "What should Maven log" dispute.
I agree with Gary that Maven is very chatty by default, but I don't think `log4j-changelog-maven-plugin` is much more chattier then the rest.

We should probably write a Maven-to-Log4j logging bridge, so that we can filter out messages better. Ant has many verbosity levels, while Maven has just the "chatty" setting and "very chatty".

**Comment by vy** [comment]
I am closing the issue due to lack of interest. Please feel free to re-open it when you submit a PR.
